config/routes.rb
Rails.application.routes.draw do

  get 'accept_user_input' => 'dashboard#index'
  post 'submit_user_input' => 'dashboard#submit'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    call_api(params['user_input'])
  end

  def submit
    call_api(params['user_input_form']['user_input'])
    render :action => 'index'
  end

  def call_api(input)
    @result = nil
    if input
      api_key = 'd8372703aeb94b7035ce12d07f61ba84'
      api_id = 'ceadf6d2'
      query = input
      api_url = "https://api.nutritionix.com/v1_1/search/#{query}?results=0:10&fields=item_name,brand_name,item_id,nf_calories,nf_carbohydrates,nf_protein,nf_carbs&appId=#{api_id}&appKey=#{api_key}"
      @result = HTTParty.get(api_url)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_results.html.erb
<ol>
  <% @result['hits'].each do |result| %>
    <li>
      <%= result %>
    </li>
  <% end %>
</ol>

app/views/dashboard/index.html.erb
<%= form_for :user_input_form, url: submit_user_input_path do |f| %>
  <%= f.text_field :user_input %>
  <%= f.submit %>
<% end %>

<br>
<br>
<b>Params:</b> <%= params %><br>

<br>
<br>
<b>HTTParty Result:</b> <%= render :partial => 'results' %>

app/views/dashboard/submit.html.erb
There is nothing here.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AcceptUserInput</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>